import Head from "next/head";
import Image from "next/image";
import CSVReader from "react-csv-reader";
import styles from "../styles/Home.module.css";
import emojiRegex from "emoji-regex";
import { useState } from "react";
import { CSVLink } from "react-csv";

export default function Home() {
  const [data, setData] = useState([]);

  const papaparseOptions = {
    header: true,
    dynamicTyping: true,
    skipEmptyLines: true,
    transformHeader: (header) => header.toLowerCase().replace(/\W/g, "_"),
  };

  const handleForce = (data, fileInfo) => {
    const tweets = data.map((item) => item.title);

    const regex = emojiRegex();

    const textEmoji =
      "Selamat Pagi Dulur ðŸ‘‹ðŸ‘‹  @pidpolreskediri  #ntmcpolri #rtmcjatim #ditlantaspoldajatim #polantasindonesia #polantasjatim #polantaskediri #satlantasreskediri #JatimBermasker #ayopakaimasker #opsamannusallsemeru2021 #opsamannusall2021 #polripresisi #opskeselamatansemeru2021";
    const extractEmoji = textEmoji.match(regex);

    const extractedEmoji = tweets
      .filter((tweet) => {
        return tweet.match(regex);
      })
      .map((tweet) => {
        return tweet.match(regex);
      });

    const merged = [].concat.apply([], extractedEmoji);

    console.log(merged);

    const groupEmojis = merged.reduce((acc, curr) => {
      acc[curr] = (acc[curr] || 0) + 1;
      return acc;
    }, {});

    setData(groupEmojis);
  };

  const csvData = Object.keys(data).map((key) => {
    return {
      emoji: key,
      count: data[key],
    };
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Emoji Counter From Text</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <CSVReader
          cssClass="react-csv-input"
          label="Select CSV with secret Death Star statistics"
          onFileLoaded={handleForce}
          parserOptions={papaparseOptions}
        />
        <p>and then open the console</p>
      </div>
      <button>
        <CSVLink data={csvData} filename="emoji-counts">
          Download CSV
        </CSVLink>
      </button>
      <table>
        {Object.keys(data).map((key, idx) => {
          return (
            <tr key={idx}>
              <td>{key}</td>
              <td>{data[key]}</td>
            </tr>
          );
        })}
      </table>
    </div>
  );
}
